### ISSUE TITLE
Issues with Mask Filling

### ISSUE THREAD

**Issue by muggin** [ShuyangCao/cliff_summ#3]
I encountered the following errors when trying to run the `lm_mask_fill.py` script.

```Traceback (most recent call last):
  File "../../data_construction/neg_mask_regen/lm_mask_fill.py", line 175, in <module>
    main()
  File "../../data_construction/neg_mask_regen/lm_mask_fill.py", line 164, in main
    new_summary = bart.fill_mask(inputs, topk=args.topk, beam=5, match_source_len=False)
  File "/export/home/cliff_summ/data/fairseqs/fairseq/models/bart/hub_interface.py", line 196, in fill_mask
    batch_hypos = self.generate(batch_tokens, **generate_kwargs)
  File "/export/home/cliff_summ/data/fairseqs/fairseq/models/bart/hub_interface.py", line 105, in generate
    return super().generate(
  File "/export/home/cliff_summ/data/fairseqs/fairseq/hub_utils.py", line 171, in generate
    translations = self.task.inference_step(
  File "/export/home/cliff_summ/data/fairseqs/fairseq/tasks/fairseq_task.py", line 450, in inference_step
    return generator.generate(
  File "/root/miniconda3/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 26, in decorate_context
    return func(*args, **kwargs)
  File "/export/home/cliff_summ/data/fairseqs/fairseq/sequence_generator.py", line 176, in generate
    return self._generate(sample, **kwargs)
  File "/export/home/cliff_summ/data/fairseqs/fairseq/sequence_generator.py", line 341, in _generate
    lprobs, tokens, scores = self._prefix_tokens(
  File "/export/home/cliff_summ/data/fairseqs/fairseq/sequence_generator.py", line 547, in _prefix_tokens
    prefix_lprobs = lprobs.gather(-1, prefix_toks.unsqueeze(-1))
RuntimeError: Size does not match at dimension 0 expected index [120, 1] to be smaller than src [100, 50265] apart from dimension 1```

**Comment by ShuyangCao** [comment]
I think this is an issue related to Fairseq. Can you try install the environment with the added requirement file and see if it works?

**Comment by muggin** [comment]
Thanks for the response. I checked the environment with the associated requirements file and the errors still happens.

**Comment by ShuyangCao** [comment]
Just had time to look into the problem. The underlying issue was incidentally fixed when I was working on another project.

Please go to `<site-packpages>/fairseq/hub_utils.py` and check the code starting from Line 167:

```python
        results = []
        for batch in self._build_batches(tokenized_sentences, skip_invalid_size_inputs):
            batch = utils.apply_to_sample(lambda t: t.to(self.device), batch)
            translations = self.task.inference_step(
                generator, self.models, batch, **inference_step_args
            )
            for id, hypos in zip(batch["id"].tolist(), translations):
                results.append((id, hypos))
```

Change to:

```python
        results = []
        sid = 0
        for batch in self._build_batches(tokenized_sentences, skip_invalid_size_inputs):
            batch = utils.apply_to_sample(lambda t: t.to(self.device), batch)
            batch_size = batch["net_input"]["src_tokens"].size(0)
            if "prefix_tokens" in inference_step_args:
                batch_inference_step_args = copy.copy(inference_step_args)
                batch_inference_step_args["prefix_tokens"] = inference_step_args["prefix_tokens"][sid:sid + batch_size]
                sid += batch_size
            else:
                batch_inference_step_args = inference_step_args
            translations = self.task.inference_step(
                generator, self.models, batch, **batch_inference_step_args
            )
            for id, hypos in zip(batch["id"].tolist(), translations):
                results.append((id, hypos))
```
