### ISSUE TITLE
multi-card training crush on custom dataset 

### ISSUE THREAD

**Issue by ElderWanng** [ShuyangCao/cliff_summ#6]
I gathered negative data and positive data on gigaword. 
The training crushed when I set 2 cards. Here is log:
```
Traceback (most recent call last):
  File "/ext3/miniconda3/envs/syslowcon/bin/fairseq-train", line 33, in <module>
    sys.exit(load_entry_point('fairseq', 'console_scripts', 'fairseq-train')())
  File "/scratch/tw2112/codes/fairseq/fairseq_cli/train.py", line 392, in cli_main
    distributed_utils.call_main(cfg, main)
  File "/scratch/tw2112/codes/fairseq/fairseq/distributed_utils.py", line 313, in call_main
    torch.multiprocessing.spawn(
  File "/ext3/miniconda3/envs/syslowcon/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 230, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/ext3/miniconda3/envs/syslowcon/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
    while not context.join():
  File "/ext3/miniconda3/envs/syslowcon/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 130, in join
    raise ProcessExitedException(
torch.multiprocessing.spawn.ProcessExitedException: process 0 terminated with signal SIGKILL

```
From this I can't get any useful information
I know use spawn to start DDP will lose some error message, so I switch to 1 card training. But this time the training runs well, only print warning I mentioned in #4 . 

Same problem also happens on xsum datasets downloaded from the google drive

**Comment by ShuyangCao** [comment]
This is weird. Did the training progress several steps before throwing the errors? Also, if you are using a cluster, how much memory did you request? I didn't optimize the memory usage for the data loader, so it could go up to 60G when using two cards.

**Comment by ElderWanng** [comment]
@ShuyangCao you are right... I applied 50GB RAM per node...
Just because 2 cards, store 2 datasets in memory, then BOOM.. and that's why it works for single card training. 
Request 100G, problem solved.
